### ISSUE TITLE
NoSuchMethodError: java.lang.Long.parseUnsignedLong

### ISSUE THREAD

**Issue by mwgkgk** [LuxLang/lux#31]
Both [helloworld](https://luxlang.gitbooks.io/the-lux-programming-language/content/chapter1.html) and [tutorial1](https://github.com/LuxLang/tutorial1) fail on `lein lux build` with:
```
[BUILD BEGIN]
Exception in thread "main" java.lang.NoSuchMethodError: java.lang.Long.parseUnsignedLong(Ljava/lang/String;)J
        at lux.parser$fn__6996.invoke(parser.clj:80)
        at lux.base$bind$fn__1304.invoke(base.clj:385)
        at lux.parser$repeat_PERCENT_$fn__6923.invoke(parser.clj:19)
        at lux.base$bind$fn__1304.invoke(base.clj:382)
        at lux.base$bind$fn__1304.invoke(base.clj:382)
        at lux.base$bind$fn__1304.invoke(base.clj:385)
        at lux.parser$repeat_PERCENT_$fn__6923.invoke(parser.clj:19)
        at lux.base$bind$fn__1304.invoke(base.clj:382)
        at lux.parser$repeat_PERCENT_$fn__6923.invoke(parser.clj:31)
        at lux.base$bind$fn__1304.invoke(base.clj:382)
        at lux.parser$repeat_PERCENT_$fn__6923.invoke(parser.clj:31)
        at lux.base$bind$fn__1304.invoke(base.clj:382)
        at lux.parser$repeat_PERCENT_$fn__6923.invoke(parser.clj:31)
        at lux.base$bind$fn__1304.invoke(base.clj:382)
        at lux.parser$repeat_PERCENT_$fn__6923.invoke(parser.clj:31)
        at lux.base$bind$fn__1304.invoke(base.clj:382)
        at lux.base$bind$fn__1304.invoke(base.clj:382)
        at lux.base$bind$fn__1304.invoke(base.clj:385)
        at lux.base$bind$fn__1304.invoke(base.clj:382)
        at lux.base$exhaust_PERCENT_$fn__1855.invoke(base.clj:665)
        at lux.base$exhaust_PERCENT_$fn__1855.invoke(base.clj:667)
        at lux.base$exhaust_PERCENT_$fn__1855.invoke(base.clj:667)
        at lux.base$exhaust_PERCENT_$fn__1855.invoke(base.clj:667)
        at lux.base$exhaust_PERCENT_$fn__1855.invoke(base.clj:667)
        at lux.base$exhaust_PERCENT_$fn__1855.invoke(base.clj:667)
        at lux.base$exhaust_PERCENT_$fn__1855.invoke(base.clj:667)
        at lux.base$with_writer$fn__2154.invoke(base.clj:982)
        at lux.compiler$fn__28796$compile_module__28797$fn__28798$fn__28804$fn__28806$fn__28809$fn__28812$fn__28828$fn__28831.invoke(compiler.clj:210)
        at lux.base$bind$fn__1304.invoke(base.clj:385)
        at lux.base$bind$fn__1304.invoke(base.clj:385)
        at lux.base$bind$fn__1304.invoke(base.clj:385)
        at lux.base$bind$fn__1304.invoke(base.clj:385)
        at lux.base$bind$fn__1304.invoke(base.clj:385)
        at lux.base$run_state.invoke(base.clj:919)
        at lux.base$_BAR_eitherL$fn__3023.invoke(base.clj:1520)
        at lux.base$bind$fn__1304.invoke(base.clj:385)
        at lux.base$bind$fn__1304.invoke(base.clj:382)
        at lux.base$bind$fn__1304.invoke(base.clj:385)
        at lux.compiler$fn__28911$compile_program__28912.invoke(compiler.clj:263)
        at lux$_main.doInvoke(lux.clj:29)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at lux.main(Unknown Source)
[BUILD END]
```
`lein lux repl` fails with
```
clojure.lang.ArityException: Wrong number of args (2) passed to: utils/repl-path
 at clojure.lang.AFn.throwArity (AFn.java:429)
    clojure.lang.AFn.invoke (AFn.java:36)
    leiningen.lux.repl$repl.invokeStatic (repl.clj:9)
    leiningen.lux.repl$repl.invoke (repl.clj:8)
    leiningen.lux$lux.invokeStatic (lux.clj:14)
    leiningen.lux$lux.doInvoke (lux.clj:10)
    clojure.lang.RestFn.invoke (RestFn.java:423)
    clojure.lang.Var.invoke (Var.java:383)
    clojure.lang.AFn.applyToHelper (AFn.java:156)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.core$apply.invoke (core.clj:641)
    leiningen.core.main$partial_task$fn__5932.doInvoke (main.clj:272)
    clojure.lang.RestFn.applyTo (RestFn.java:139)
    clojure.lang.AFunction$1.doInvoke (AFunction.java:29)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.core$apply.invoke (core.clj:641)
    leiningen.core.main$apply_task.invokeStatic (main.clj:322)
    leiningen.core.main$apply_task.invoke (main.clj:308)
    leiningen.core.main$resolve_and_apply.invokeStatic (main.clj:328)
    leiningen.core.main$resolve_and_apply.invoke (main.clj:324)
    leiningen.core.main$_main$fn__5998.invoke (main.clj:401)
    leiningen.core.main$_main.invokeStatic (main.clj:394)
    leiningen.core.main$_main.doInvoke (main.clj:391)
    clojure.lang.RestFn.invoke (RestFn.java:421)
    clojure.lang.Var.invoke (Var.java:383)
    clojure.lang.AFn.applyToHelper (AFn.java:156)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.core$apply.invokeStatic (core.clj:646)
    clojure.main$main_opt.invokeStatic (main.clj:314)
    clojure.main$main_opt.invoke (main.clj:310)
    clojure.main$main.invokeStatic (main.clj:421)
    clojure.main$main.doInvoke (main.clj:384)
    clojure.lang.RestFn.invoke (RestFn.java:457)
    clojure.lang.Var.invoke (Var.java:394)
    clojure.lang.AFn.applyToHelper (AFn.java:165)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.main.main (main.java:37)
```
```
$ lein --version
Leiningen 2.7.1 on Java 1.7.0_151 OpenJDK 64-Bit Server VM
```
Running Archlinux. No experience with Java or Clojure, so this might be something trivial. Clojure helloworld works fine, as does repl. Luxc version in `project.clj` is `0.5.0`.

**Comment by mwgkgk** [comment]
As a followup question, what is the best way to build your projects against the git version of Lux? This probably has a simple answer involving `:plugin-repositories`, but I failed to find one, perhaps you could save me from a deeper dive into Leiningen docs

**Comment by LuxLang** [comment]
> Exception in thread "main" java.lang.NoSuchMethodError: java.lang.Long.parseUnsignedLong(Ljava/lang/String;)J

This is because the compiler currently needs a method in java.lang.Long that is only available on Java 8.

You'll have to upgrade your JRE.

Regarding the REPL... You've just found a bug. Thanks!

I'll try to fix it and push a patched version later.

> As a followup question, what is the best way to build your projects against the git version of Lux?

You could clone the repo and build everything yourself.

Doing `lein install` on all the repos should keep you up-to-date without needing my help.

`lein install` on _luxc_ will automatically compile the _luxc compiler_, so no extra step will be needed there.

**Comment by mwgkgk** [comment]
Thank you. Have to say, love the project. So many sexy features. Such great docs. It has great future.
