### ISSUE TITLE
Exception when trying to build

### ISSUE THREAD

**Issue by Tzeroxik** [LuxLang/lux#41]
tried building a lux project and got this exception when using both `lein lux build` and `lein lux auto build`

```Java
Exception in thread "main" java.lang.AssertionError: Assert failed: (not (nil? %))                                              at leiningen.lux.utils$find_compiler_path.invokeStatic(utils.clj:35) at leiningen.lux.utils$find_compiler_path.invoke(utils.clj:35) at leiningen.lux.utils$compile_path.invokeStatic(utils.clj:66) at leiningen.lux.utils$compile_path.invoke(utils.clj:66) 
at leiningen.lux.builder$build.invokeStatic(builder.clj:8) at leiningen.lux.builder$build.invoke(builder.clj:6)                                                                    at leiningen.lux$lux.invokeStatic(lux.clj:12)  at leiningen.lux$lux.doInvoke(lux.clj:10)                                                                               at clojure.lang.RestFn.invoke(RestFn.java:423) at clojure.lang.Var.invoke(Var.java:383)                                                                                at clojure.lang.AFn.applyToHelper(AFn.java:156) at clojure.lang.Var.applyTo(Var.java:700)                                                                               at clojure.core$apply.invokeStatic(core.clj:648) at clojure.core$apply.invoke(core.clj:641)                                                                              at leiningen.core.main$partial_task$fn__4667.doInvoke(main.clj:284) at clojure.lang.RestFn.applyTo(RestFn.java:139) at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)                                                                 at clojure.lang.RestFn.applyTo(RestFn.java:137) at clojure.core$apply.invokeStatic(core.clj:648)                                                                        at clojure.core$apply.invoke(core.clj:641) at leiningen.core.main$apply_task.invokeStatic(main.clj:334)                                                            at leiningen.core.main$apply_task.invoke(main.clj:320)  at leiningen.core.main$resolve_and_apply.invokeStatic(main.clj:340) at leiningen.core.main$resolve_and_apply.invoke(main.clj:336) at leiningen.core.main$_main$fn__4734.invoke(main.clj:420) at leiningen.core.main$_main.invokeStatic(main.clj:411) at leiningen.core.main$_main.doInvoke(main.clj:408) at clojure.lang.RestFn.invoke(RestFn.java:421) at clojure.lang.Var.invoke(Var.java:383) at clojure.lang.AFn.applyToHelper(AFn.java:156) at clojure.lang.Var.applyTo(Var.java:700) at clojure.core$apply.invokeStatic(core.clj:646)  at clojure.main$main_opt.invokeStatic(main.clj:314) at clojure.main$main_opt.invoke(main.clj:310) at clojure.main$main.invokeStatic(main.clj:421) at clojure.main$main.doInvoke(main.clj:384)  at clojure.lang.RestFn.invoke(RestFn.java:457)at clojure.lang.Var.invoke(Var.java:394) at clojure.lang.AFn.applyToHelper(AFn.java:165)  at clojure.lang.Var.applyTo(Var.java:700)  at clojure.main.main(main.java:37)      
```
my project.clj

```Clojure
(defproject lux/program1 "0.1.0-SNAPSHOT"
  :plugins [[com.github.luxlang/lein-luxc "0.5.0"]]
  :dependencies [[io.vertx/vertx-web "3.0.0"]]
  :source-paths ["source"]
  :lux {:program "main"}
  )
```

**Comment by LuxLang** [comment]
Ooh wee...

Another one falls into that pit.

You're lucky.
Someone else had that issue last week and we managed to figure it out.

Basically, the lux-lein plugin is not playing well with the latest version of Leiningen.

To avoid any trouble using Lux right now, it's best to use Leiningen 2.7.1 and Java 8.

v0.6 will be updated to work with the latest Leiningen, and Java 9; but for now it's best to go with the versions I mentioned.

**Comment by Tzeroxik** [comment]
Okay, It works fine now, thanks!
